-- ====================================================================
-- ESQUEMA COMPLETO DE BASE DE DATOS PARA SUPABASE - KINASE ACADEMY
-- Ejecutar en: Supabase Dashboard > SQL Editor
-- ====================================================================

-- --------------------------------------------------------------------
-- 1. Tabla de Diagnósticos y Leads (leads)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.leads (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    name text NOT NULL,
    lastname text NOT NULL,
    email text NOT NULL,
    phone text NOT NULL,
    career text NOT NULL,
    result text,
    answers text
);

ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permitir insercion anonima de leads" ON public.leads;
CREATE POLICY "Permitir insercion anonima de leads" 
ON public.leads 
FOR INSERT 
WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir lectura de leads a usuarios autenticados" ON public.leads;
CREATE POLICY "Permitir lectura de leads a usuarios autenticados" 
ON public.leads 
FOR SELECT 
USING (auth.role() = 'authenticated');

-- --------------------------------------------------------------------
-- 2. Tabla de Foro y Experiencias de Comunidad (community_posts)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.community_posts (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    author_name text NOT NULL,
    subject text NOT NULL,
    cathedra text,
    rating integer DEFAULT 5,
    content text NOT NULL,
    upvotes integer DEFAULT 0
);

ALTER TABLE public.community_posts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Lectura publica de experiencias" ON public.community_posts;
CREATE POLICY "Lectura publica de experiencias" 
ON public.community_posts 
FOR SELECT 
USING (true);

DROP POLICY IF EXISTS "Insercion para usuarios autenticados" ON public.community_posts;
CREATE POLICY "Insercion para usuarios autenticados" 
ON public.community_posts 
FOR INSERT 
WITH CHECK (auth.role() = 'authenticated');

-- --------------------------------------------------------------------
-- 3. Tabla de Avisos y Novedades (announcements)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.announcements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    title text NOT NULL,
    content text NOT NULL,
    tag text DEFAULT 'General'::text,
    link text
);

ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permitir lectura publica de anuncios" ON public.announcements;
CREATE POLICY "Permitir lectura publica de anuncios" 
ON public.announcements 
FOR SELECT 
USING (true);

DROP POLICY IF EXISTS "Permitir insercion de anuncios a usuarios autenticados" ON public.announcements;
CREATE POLICY "Permitir insercion de anuncios a usuarios autenticados" 
ON public.announcements 
FOR INSERT 
WITH CHECK (auth.role() = 'authenticated');

-- --------------------------------------------------------------------
-- 4. Índices para optimizar rendimiento de consultas
-- --------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_announcements_created_at ON public.announcements(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_community_posts_created_at ON public.community_posts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_leads_created_at ON public.leads(created_at DESC);
