-- ====================================================================
-- SCRIPT DE CONFIGURACIÓN DE TABLA DE AVISOS Y NOVEDADES EN SUPABASE
-- Ejecutar este script en el editor SQL de tu panel de Supabase
-- ====================================================================

-- 1. Crear la tabla de anuncios si no existe
CREATE TABLE IF NOT EXISTS public.announcements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    title text NOT NULL,
    content text NOT NULL,
    tag text DEFAULT 'General'::text,
    link text
);

-- 2. Habilitar la seguridad de fila (RLS)
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;

-- 3. Crear política para que CUALQUIER USUARIO (público, no registrado, etc.) pueda VER los anuncios
DROP POLICY IF EXISTS "Permitir lectura publica de anuncios" ON public.announcements;
CREATE POLICY "Permitir lectura publica de anuncios" 
ON public.announcements 
FOR SELECT 
USING (true);

-- 4. Crear política para que cualquier usuario pueda PUBLICAR anuncios (puedes restringirlo después si lo deseas)
DROP POLICY IF EXISTS "Permitir insercion publica de anuncios" ON public.announcements;
CREATE POLICY "Permitir insercion publica de anuncios" 
ON public.announcements 
FOR INSERT 
WITH CHECK (true);
